apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-labled
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
  annotations:
    codefresh.io/product: test-product
spec:
  project: default
  destination:
    name: in-cluster
    namespace: stage-ns
  source:
    path: .
    repoURL: https://github.com/alina-codefresh/test_date_git_source.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
